version: '3.8'
services:
  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile.development
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    image: astuto_db:development
    ports:
      - ${DOCKER_DB_PORT:-5432}:5432
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.production
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - db
    env_file:
      - .env
    image: astuto_web:production
    ports:
      - ${DOCKER_APP_PORT:-3000}:3000
volumes:
  db-data:
