version: '3.8'
services:
  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile.development
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    image: astuto_db:development
    ports:
      - ${DOCKER_DB_PORT:-5432}:5432
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.development
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - db
    env_file:
      - .env
    image: astuto_web:development
    volumes:
      - type: bind
        source: .
        target: /app/
        consistency: cached
      - type: volume
        source: web-bundle
        target: /usr/local/bundle/
      - type: volume
        source: web-node_modules
        target: /app/node_modules/
      - type: volume
        source: web-public-packs
        target: /app/public/packs/
      - type: volume
        source: web-tmp-cache
        target: /app/tmp/cache/
      - /app/.bundle/
      - /app/.git/
      - /app/docker/
      - /app/log/
      - /app/tmp/pids/
      - /app/vendor/bundle/
    ports:
      - ${DOCKER_WEB_PORT:-3000}:3000
volumes:
  db-data:
  web-bundle:
  web-node_modules:
  web-public-packs:
  web-tmp-cache:
