version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      # - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - UPDATE=0
      - ENVIRONMENT
      - SECRET_KEY_BASE
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - DATABASE_HOST
      - EMAIL_CONFIRMATION
      - APP_NAME
      - SHOW_LOGO
      - POSTS_PER_PAGE
      - SCS_SERVER
      - SCS_KEY
      - SCS_SECRET
    volumes:
      - .:/astuto
    ports:
      - "3000:3000"
    depends_on:
      - db