---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    tier: web
spec:
  ports:
    - name: nginx
      port: 80
  selector:
    tier: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    tier: web
spec:
  selector:
    matchLabels:
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
        - name: rails
          args: ["bundle", "exec", "rails", "server", "-u", "puma", "-b", "0.0.0.0"]
          env:
            # App
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: app_name
            - name: EMAIL_CONFIGRATION
              value: "no"
            - name: SHOW_LOGO
              value: "no"
            - name: POSTS_PER_PAGE
              value: "15"
            # Database
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: database_host
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: database_name
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: database_password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: database_user
            # SCS
            - name: SCS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: scs_key
            - name: SCS_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: scs_secret
            - name: SCS_SERVER
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: scs_server
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: secret_key_base
          envFrom:
            - configMapRef:
                name: env
          ports:
            - name: rails
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 120
            successThreshold: 1
            failureThreshold: 20
        - name: nginx
          image: nginx:1.18.0-alpine
          ports:
            - name: nginx
              containerPort: 80
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          volumeMounts:
            - name: nginx-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-nginx-conf
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
...
