---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    tier: db
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    tier: db
spec:
  serviceName: db
  selector:
    matchLabels:
      tier: db
  replicas: 1
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
        - name: postgres
          image: astuto_db:development
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: database_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-feedbacks-secret
                  key: database_password
            - name: POSTGRES_INITDB_ARGS
              value: --encoding=UTF-8
          envFrom:
            - configMapRef:
                name: env
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          hostPath:
            path: astuto_db-data
            type: DirectoryOrCreate
  volumeClaimTemplates: []
...
