bases:
  - ../../base
commonLabels:
  env: development
configMapGenerator:
  - name: env
    env: configmaps/env
# NOTE: namePrefix, namespaceをbaseの下に置くとmergeがうまくいかないのでここに書く
namePrefix: cloud-feedbacks-
namespace: cloud-feedbacks-development
patchesStrategicMerge:
  - services/web.yaml
resources:
  - secrets/secret.yaml
  - services/db.yaml
  - ingress.yaml
