apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rails
          image: $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPOSITORY:$TAG
          resources:
            requests:
              cpu: 400m
              memory: 800Mi
            limits:
              cpu: 400m
              memory: 800Mi
        - name: nginx
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: nginx-default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-default-conf
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
