commonLabels:
  app: cloud-feedbacks
configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf=configmaps/nginx/nginx.conf
      - default.conf=configmaps/nginx/default.conf
      - default-http.conf=configmaps/nginx/default-http.conf
resources:
  - services/web.yaml
